[project]
name = "winidjango"
version = "4.15.37"
description = "A utility package for django"
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
license-files = [
  "LICENSE",
]
authors = [
  { name = "Winipedia", email = "winipedia@gmx.de" },
]
maintainers = [
  { name = "Winipedia", email = "winipedia@gmx.de" },
]
keywords = [
  "pyrig",
]
classifiers = [
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Typing :: Typed",
]
dependencies = [
  "django>=6.1.1",
  "django-stubs-ext>=6.1.1",
  "filelock>=4.0.1",
  "polars>=1.44.2",
  "pyrig>=18.85.1",
  "pyrig-runtime>=3.23.45",
  "winiutils>=4.14.72",
]

[project.urls]
Changelog = "https://github.com/Winipedia/winidjango/releases"
Documentation = "https://Winipedia.github.io/winidjango"
Homepage = "https://github.com/Winipedia/winidjango"
Issues = "https://github.com/Winipedia/winidjango/issues"
Source = "https://github.com/Winipedia/winidjango"

[project.scripts]
winidjango = "pyrig_runtime.rig.cli.main:main"

[dependency-groups]
dev = [
  "actionlint-py>=1.7.12.25",
  "bandit>=1.9.4",
  "deptry>=0.25.1",
  "detect-secrets>=1.5.0",
  "django-stubs>=6.1.1",
  "mkdocstrings[python]>=1.0.6",
  "pre-commit-hooks>=6.0.0",
  "prek>=0.5.3",
  "pyflakes>=3.4.0",
  "pyrig>=18.85.1",
  "pyrig-codeql>=1.0.0",
  "pyrig-pypi>=3.20.28",
  "pytest>=9.1.1",
  "pytest-cov>=7.1.0",
  "pytest-django>=4.14.0",
  "pytest-mock>=3.15.1",
  "pytest-randomly>=5.0.0",
  "pytest-xdist>=3.8.0",
  "ruff>=0.16.8",
  "rumdl>=0.2.75",
  "ryl>=0.22.0",
  "shellcheck-py>=0.11.0.1",
  "shfmt-py>=4.2.0",
  "tombi>=1.5.5",
  "ty>=0.0.83",
  "types-defusedxml>=0.7.0.20260504",
  "types-tqdm>=4.70.0.20260906",
  "typos>=1.50.2",
  "zensical>=0.0.64",
  "zizmor>=1.30.1",
]

[build-system]
requires = [
  "uv-build",
]
build-backend = "uv_build"

[tool.deptry]
root = "src"

[tool.deptry.per_rule_ignores]
DEP002 = [
  "pyrig-runtime",
]

[tool.pytest]
addopts = [
  "--cov-branch",
  "--cov-fail-under=90",
  "--cov-report=term-missing:skip-covered",
  "--cov=winidjango",
  "--dist=worksteal",
  "--numprocesses=auto",
  "--report-chars=a",
]
filterwarnings = [
  "error",
]
strict = true
testpaths = [
  "tests",
]

[tool.ruff]
exclude = [
  "**/migrations/*.py",
]

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
ignore = [
  "CPY001",
]
select = [
  "ALL",
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
  "S101",
]

[tool.ruff.lint.pydocstyle]
convention = "google"
